apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hass.fullname" . }}-secrets
type: Opaque
data:
    {{ if .Values.watson_iot.enabled }}
    organization: {{ .Values.watson_iot.organization | b64enc | quote}}
    type: {{ .Values.watson_iot.type | b64enc | quote }}
    id: {{ .Values.watson_iot.id | b64enc | quote }}
    token: {{ .Values.watson_iot.token | b64enc | quote}}
    {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "hass.fullname" . }}-state-dir
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.hass.storage.class }}
  labels:
    app: {{ template "hass.name" . }}-hass
    chart: {{ template "hass.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.hass.storage.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "hass.fullname" . }}
  labels:
    app: {{ template "hass.name" . }}-hass
    chart: {{ template "hass.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "hass.name" . }}-hass
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "hass.name" . }}-hass
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: {{ template "hass.fullname" . }}-volume
          persistentVolumeClaim:
            claimName: {{ template "hass.fullname" . }}-state-dir
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}/{{.Values.hass.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{ if .Values.watson_iot.enabled }}
            - name: WATSON_IOT_ENABLED
              value: "1"
            - name: WATSON_IOT_ORG
              valueFrom:
                secretKeyRef:
                  name: {{ template "hass.fullname" . }}-secrets
                  key: organization
            - name: WATSON_IOT_TYPE
              valueFrom:
                secretKeyRef:
                  name: {{ template "hass.fullname" . }}-secrets
                  key: type
            - name: WATSON_IOT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "hass.fullname" . }}-secrets
                  key: id
            - name: WATSON_IOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "hass.fullname" . }}-secrets
                  key: token
            {{- end}}
          volumeMounts:
            - name: {{ template "hass.fullname" . }}-volume
              mountPath: "/shared"
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "hass.fullname" . }}-hass
  labels:
    app: {{ template "hass.name" . }}-hass
    chart: {{ template "hass.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
  - port: 8123
    targetPort: 8123
    name: hass
    protocol: TCP
  selector:
    app: {{ template "hass.name" . }}-hass
    release: {{ .Release.Name }}
